/* tslint:disable */
/* eslint-disable */
/**
 * Recommendation Service API
 * API for personalized travel itinerary recommendations and social graph management.  ## Authentication  All endpoints require authentication using Google Cloud Identity Platform (Firebase Authentication). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItineraryEventDTO
 */
export interface ItineraryEventDTO {
    /**
     * 
     * @type {number}
     * @memberof ItineraryEventDTO
     */
    itineraryId?: number;
    /**
     * 
     * @type {string}
     * @memberof ItineraryEventDTO
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ItineraryEventDTO
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ItineraryEventDTO
     */
    locationNames?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ItineraryEventDTO
     */
    likesCount?: number;
    /**
     * 
     * @type {string}
     * @memberof ItineraryEventDTO
     */
    eventType?: string;
}

/**
 * Check if a given object implements the ItineraryEventDTO interface.
 */
export function instanceOfItineraryEventDTO(value: object): value is ItineraryEventDTO {
    return true;
}

export function ItineraryEventDTOFromJSON(json: any): ItineraryEventDTO {
    return ItineraryEventDTOFromJSONTyped(json, false);
}

export function ItineraryEventDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItineraryEventDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'itineraryId': json['itineraryId'] == null ? undefined : json['itineraryId'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'locationNames': json['locationNames'] == null ? undefined : json['locationNames'],
        'likesCount': json['likesCount'] == null ? undefined : json['likesCount'],
        'eventType': json['eventType'] == null ? undefined : json['eventType'],
    };
}

export function ItineraryEventDTOToJSON(json: any): ItineraryEventDTO {
    return ItineraryEventDTOToJSONTyped(json, false);
}

export function ItineraryEventDTOToJSONTyped(value?: ItineraryEventDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itineraryId': value['itineraryId'],
        'title': value['title'],
        'description': value['description'],
        'locationNames': value['locationNames'],
        'likesCount': value['likesCount'],
        'eventType': value['eventType'],
    };
}

