/* tslint:disable */
/* eslint-disable */
/**
 * Recommendation Service API
 * API for personalized travel itinerary recommendations and social graph management.  ## Authentication  All endpoints require authentication using Google Cloud Identity Platform (Firebase Authentication). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LikeActionDTO
 */
export interface LikeActionDTO {
    /**
     * 
     * @type {number}
     * @memberof LikeActionDTO
     */
    itineraryId?: number;
}

/**
 * Check if a given object implements the LikeActionDTO interface.
 */
export function instanceOfLikeActionDTO(value: object): value is LikeActionDTO {
    return true;
}

export function LikeActionDTOFromJSON(json: any): LikeActionDTO {
    return LikeActionDTOFromJSONTyped(json, false);
}

export function LikeActionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LikeActionDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'itineraryId': json['itineraryId'] == null ? undefined : json['itineraryId'],
    };
}

export function LikeActionDTOToJSON(json: any): LikeActionDTO {
    return LikeActionDTOToJSONTyped(json, false);
}

export function LikeActionDTOToJSONTyped(value?: LikeActionDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itineraryId': value['itineraryId'],
    };
}

