/* tslint:disable */
/* eslint-disable */
/**
 * Recommendation Service API
 * API for personalized travel itinerary recommendations and social graph management.  ## Authentication  All endpoints require authentication using Google Cloud Identity Platform (Firebase Authentication). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocationVisitDTO
 */
export interface LocationVisitDTO {
    /**
     * 
     * @type {Array<string>}
     * @memberof LocationVisitDTO
     */
    locationNames?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof LocationVisitDTO
     */
    itineraryId?: number;
}

/**
 * Check if a given object implements the LocationVisitDTO interface.
 */
export function instanceOfLocationVisitDTO(value: object): value is LocationVisitDTO {
    return true;
}

export function LocationVisitDTOFromJSON(json: any): LocationVisitDTO {
    return LocationVisitDTOFromJSONTyped(json, false);
}

export function LocationVisitDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationVisitDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'locationNames': json['locationNames'] == null ? undefined : json['locationNames'],
        'itineraryId': json['itineraryId'] == null ? undefined : json['itineraryId'],
    };
}

export function LocationVisitDTOToJSON(json: any): LocationVisitDTO {
    return LocationVisitDTOToJSONTyped(json, false);
}

export function LocationVisitDTOToJSONTyped(value?: LocationVisitDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'locationNames': value['locationNames'],
        'itineraryId': value['itineraryId'],
    };
}

