/* tslint:disable */
/* eslint-disable */
/**
 * travel-app API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ItineraryDto,
} from '../models/index';
import {
    ItineraryDtoFromJSON,
    ItineraryDtoToJSON,
} from '../models/index';

export interface ItineraryCreatePostRequest {
    userId: number;
    itineraryDto: ItineraryDto;
}

export interface ItineraryGetGetRequest {
    userId: number;
}

/**
 * 
 */
export class ItineraryManagementApi extends runtime.BaseAPI {

    /**
     * Creates a new travel itinerary for a specific user. The itinerary must include title, destination, start date, and descriptions.
     * Create a new itinerary
     */
    async itineraryCreatePostRaw(requestParameters: ItineraryCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling itineraryCreatePost().'
            );
        }

        if (requestParameters['itineraryDto'] == null) {
            throw new runtime.RequiredError(
                'itineraryDto',
                'Required parameter "itineraryDto" was null or undefined when calling itineraryCreatePost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/itinerary/create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ItineraryDtoToJSON(requestParameters['itineraryDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Creates a new travel itinerary for a specific user. The itinerary must include title, destination, start date, and descriptions.
     * Create a new itinerary
     */
    async itineraryCreatePost(requestParameters: ItineraryCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.itineraryCreatePostRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieves all itineraries associated with a specific user ID. Returns a list of itinerary details including title, destination, start date, and descriptions.
     * Get itineraries for a user
     */
    async itineraryGetGetRaw(requestParameters: ItineraryGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ItineraryDto>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling itineraryGetGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/itinerary/get`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ItineraryDtoFromJSON));
    }

    /**
     * Retrieves all itineraries associated with a specific user ID. Returns a list of itinerary details including title, destination, start date, and descriptions.
     * Get itineraries for a user
     */
    async itineraryGetGet(requestParameters: ItineraryGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ItineraryDto>> {
        const response = await this.itineraryGetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
