/* tslint:disable */
/* eslint-disable */
/**
 * Travel App API
 * API for managing travel itineraries, locations, and social interactions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ItineraryDto,
  ItinerarySearchDto,
  ItinerarySearchResponseDto,
} from '../models/index';
import {
    ItineraryDtoFromJSON,
    ItineraryDtoToJSON,
    ItinerarySearchDtoFromJSON,
    ItinerarySearchDtoToJSON,
    ItinerarySearchResponseDtoFromJSON,
    ItinerarySearchResponseDtoToJSON,
} from '../models/index';

export interface ItineraryCreatePostRequest {
    itineraryDto: ItineraryDto;
}

export interface ItinerarySearchPostRequest {
    itinerarySearchDto: ItinerarySearchDto;
}

/**
 * 
 */
export class ItineraryManagementApi extends runtime.BaseAPI {

    /**
     * Creates a new travel itinerary for the authenticated user. Requires authentication. The itinerary must include title, destination, start date, and descriptions.
     * Create a new itinerary
     */
    async itineraryCreatePostRaw(requestParameters: ItineraryCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['itineraryDto'] == null) {
            throw new runtime.RequiredError(
                'itineraryDto',
                'Required parameter "itineraryDto" was null or undefined when calling itineraryCreatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/itinerary/create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ItineraryDtoToJSON(requestParameters['itineraryDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Creates a new travel itinerary for the authenticated user. Requires authentication. The itinerary must include title, destination, start date, and descriptions.
     * Create a new itinerary
     */
    async itineraryCreatePost(requestParameters: ItineraryCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.itineraryCreatePostRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieves all itineraries associated with the authenticated user. Requires authentication. Returns a list of itinerary details including title, destination, start date, and descriptions.
     * Get itineraries for authenticated user
     */
    async itineraryGetGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ItineraryDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/itinerary/get`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ItineraryDtoFromJSON));
    }

    /**
     * Retrieves all itineraries associated with the authenticated user. Requires authentication. Returns a list of itinerary details including title, destination, start date, and descriptions.
     * Get itineraries for authenticated user
     */
    async itineraryGetGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ItineraryDto>> {
        const response = await this.itineraryGetGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Search for itineraries based on various criteria including user name, user email, title, destination, description, and start date range. All search parameters are optional - empty/null values will be ignored. Requires authentication.
     * Search itineraries
     */
    async itinerarySearchPostRaw(requestParameters: ItinerarySearchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ItinerarySearchResponseDto>>> {
        if (requestParameters['itinerarySearchDto'] == null) {
            throw new runtime.RequiredError(
                'itinerarySearchDto',
                'Required parameter "itinerarySearchDto" was null or undefined when calling itinerarySearchPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/itinerary/search`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ItinerarySearchDtoToJSON(requestParameters['itinerarySearchDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ItinerarySearchResponseDtoFromJSON));
    }

    /**
     * Search for itineraries based on various criteria including user name, user email, title, destination, description, and start date range. All search parameters are optional - empty/null values will be ignored. Requires authentication.
     * Search itineraries
     */
    async itinerarySearchPost(requestParameters: ItinerarySearchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ItinerarySearchResponseDto>> {
        const response = await this.itinerarySearchPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
