# Auto-generated imports.tf
# This file was generated by smart-import.sh
# Only imports resources that actually exist in GCP

import {
  to = google_service_account.cloud_run_sa
  id = "projects/graphite-plane-474510-s9/serviceAccounts/travel-frontend-sa@graphite-plane-474510-s9.iam.gserviceaccount.com"
}

import {
  to = google_cloud_run_v2_service.main
  id = "projects/graphite-plane-474510-s9/locations/europe-west1/services/travel-frontend"
}

