#!/bin/bash
# Smart Import Generator - Checks which resources exist and creates imports.tf automatically

set -e

PROJECT_ID="graphite-plane-474510-s9"
REGION="europe-west1"

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║         Smart Import Generator                                ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "Checking which resources exist in GCP..."
echo ""

# Create imports.tf with header
cat > imports.tf << 'EOF'
# Auto-generated imports.tf
# This file was generated by smart-import.sh
# Only imports resources that actually exist in GCP

EOF

# Check Artifact Registry Repository (only if managed by this Terraform)
echo "[1/2] Checking Artifact Registry Repository..."
if grep -q "create_artifact_registry.*=.*true" terraform.tfvars 2>/dev/null; then
    if gcloud artifacts repositories describe docker-repo --location=${REGION} --project=${PROJECT_ID} >/dev/null 2>&1; then
        echo "  ✅ Exists - Will import"
        cat >> imports.tf << EOF
import {
  to = google_artifact_registry_repository.docker_repo[0]
  id = "projects/${PROJECT_ID}/locations/${REGION}/repositories/docker-repo"
}

EOF
    else
        echo "  ℹ️  Doesn't exist - Will create"
    fi
else
    echo "  ⏭️  Skipped (create_artifact_registry=false, using existing registry)"
fi

# Check Cloud Run Service
echo "[2/2] Checking Cloud Run Service..."
if gcloud run services describe travel-frontend --region=${REGION} --project=${PROJECT_ID} >/dev/null 2>&1; then
    echo "  ✅ Exists - Will import"
    cat >> imports.tf << EOF
import {
  to = google_cloud_run_v2_service.main
  id = "projects/${PROJECT_ID}/locations/${REGION}/services/travel-frontend"
}

EOF
else
    echo "  ℹ️  Doesn't exist - Will create"
fi

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║         ✅ imports.tf Generated!                              ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "File created: imports.tf"
echo ""
echo "This file contains import blocks only for resources that exist."
echo "Resources that don't exist will be created by Terraform."
echo ""
echo "Next: Run 'terraform apply'"
echo ""

