/* tslint:disable */
/* eslint-disable */
/**
 * comments-likes-service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LikeResponseDto
 */
export interface LikeResponseDto {
    /**
     * 
     * @type {number}
     * @memberof LikeResponseDto
     */
    itineraryId?: number;
    /**
     * 
     * @type {number}
     * @memberof LikeResponseDto
     */
    likeCount?: number;
}

/**
 * Check if a given object implements the LikeResponseDto interface.
 */
export function instanceOfLikeResponseDto(value: object): value is LikeResponseDto {
    return true;
}

export function LikeResponseDtoFromJSON(json: any): LikeResponseDto {
    return LikeResponseDtoFromJSONTyped(json, false);
}

export function LikeResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LikeResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'itineraryId': json['itineraryId'] == null ? undefined : json['itineraryId'],
        'likeCount': json['likeCount'] == null ? undefined : json['likeCount'],
    };
}

export function LikeResponseDtoToJSON(json: any): LikeResponseDto {
    return LikeResponseDtoToJSONTyped(json, false);
}

export function LikeResponseDtoToJSONTyped(value?: LikeResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itineraryId': value['itineraryId'],
        'likeCount': value['likeCount'],
    };
}

