/* tslint:disable */
/* eslint-disable */
/**
 * comments-likes-service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LikeDto
 */
export interface LikeDto {
    /**
     * 
     * @type {string}
     * @memberof LikeDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof LikeDto
     */
    userEmail?: string;
    /**
     * 
     * @type {number}
     * @memberof LikeDto
     */
    itineraryId?: number;
    /**
     * 
     * @type {Date}
     * @memberof LikeDto
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the LikeDto interface.
 */
export function instanceOfLikeDto(value: object): value is LikeDto {
    return true;
}

export function LikeDtoFromJSON(json: any): LikeDto {
    return LikeDtoFromJSONTyped(json, false);
}

export function LikeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LikeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userEmail': json['userEmail'] == null ? undefined : json['userEmail'],
        'itineraryId': json['itineraryId'] == null ? undefined : json['itineraryId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function LikeDtoToJSON(json: any): LikeDto {
    return LikeDtoToJSONTyped(json, false);
}

export function LikeDtoToJSONTyped(value?: LikeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userEmail': value['userEmail'],
        'itineraryId': value['itineraryId'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

