/* tslint:disable */
/* eslint-disable */
/**
 * travel-warnings-service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface WarningsTravelWarningsBatchPostRequest {
    requestBody: Array<string>;
}

export interface WarningsTravelWarningsContentIdGetRequest {
    contentId: string;
}

export interface WarningsTravelWarningsCountryCountryCodeDetailGetRequest {
    countryCode: string;
}

export interface WarningsTravelWarningsCountryCountryCodeGetRequest {
    countryCode: string;
}

export interface WarningsTravelWarningsGetRequest {
    activeOnly?: boolean;
}

/**
 * 
 */
export class TravelWarningsApi extends runtime.BaseAPI {

    /**
     * Returns travel warnings for a list of country codes
     * Get warnings for multiple countries
     */
    async warningsTravelWarningsBatchPostRaw(requestParameters: WarningsTravelWarningsBatchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling warningsTravelWarningsBatchPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/warnings/travel-warnings/batch`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Returns travel warnings for a list of country codes
     * Get warnings for multiple countries
     */
    async warningsTravelWarningsBatchPost(requestParameters: WarningsTravelWarningsBatchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.warningsTravelWarningsBatchPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns travel warning by Auswärtiges Amt content ID
     * Get travel warning by content ID
     */
    async warningsTravelWarningsContentIdGetRaw(requestParameters: WarningsTravelWarningsContentIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['contentId'] == null) {
            throw new runtime.RequiredError(
                'contentId',
                'Required parameter "contentId" was null or undefined when calling warningsTravelWarningsContentIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/warnings/travel-warnings/{contentId}`;
        urlPath = urlPath.replace(`{${"contentId"}}`, encodeURIComponent(String(requestParameters['contentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Returns travel warning by Auswärtiges Amt content ID
     * Get travel warning by content ID
     */
    async warningsTravelWarningsContentIdGet(requestParameters: WarningsTravelWarningsContentIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.warningsTravelWarningsContentIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns detailed travel warning with categorized content
     * Get detailed travel warning
     */
    async warningsTravelWarningsCountryCountryCodeDetailGetRaw(requestParameters: WarningsTravelWarningsCountryCountryCodeDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['countryCode'] == null) {
            throw new runtime.RequiredError(
                'countryCode',
                'Required parameter "countryCode" was null or undefined when calling warningsTravelWarningsCountryCountryCodeDetailGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/warnings/travel-warnings/country/{countryCode}/detail`;
        urlPath = urlPath.replace(`{${"countryCode"}}`, encodeURIComponent(String(requestParameters['countryCode'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Returns detailed travel warning with categorized content
     * Get detailed travel warning
     */
    async warningsTravelWarningsCountryCountryCodeDetailGet(requestParameters: WarningsTravelWarningsCountryCountryCodeDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.warningsTravelWarningsCountryCountryCodeDetailGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns travel warning for a specific country
     * Get travel warning by country code
     */
    async warningsTravelWarningsCountryCountryCodeGetRaw(requestParameters: WarningsTravelWarningsCountryCountryCodeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['countryCode'] == null) {
            throw new runtime.RequiredError(
                'countryCode',
                'Required parameter "countryCode" was null or undefined when calling warningsTravelWarningsCountryCountryCodeGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/warnings/travel-warnings/country/{countryCode}`;
        urlPath = urlPath.replace(`{${"countryCode"}}`, encodeURIComponent(String(requestParameters['countryCode'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Returns travel warning for a specific country
     * Get travel warning by country code
     */
    async warningsTravelWarningsCountryCountryCodeGet(requestParameters: WarningsTravelWarningsCountryCountryCodeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.warningsTravelWarningsCountryCountryCodeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all travel warnings stored in the system
     * Get all travel warnings
     */
    async warningsTravelWarningsGetRaw(requestParameters: WarningsTravelWarningsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['activeOnly'] != null) {
            queryParameters['activeOnly'] = requestParameters['activeOnly'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/warnings/travel-warnings`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Returns all travel warnings stored in the system
     * Get all travel warnings
     */
    async warningsTravelWarningsGet(requestParameters: WarningsTravelWarningsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.warningsTravelWarningsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Triggers manual fetch of latest warnings from Auswärtiges Amt API
     * Manually refresh travel warnings
     */
    async warningsTravelWarningsRefreshPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/warnings/travel-warnings/refresh`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Triggers manual fetch of latest warnings from Auswärtiges Amt API
     * Manually refresh travel warnings
     */
    async warningsTravelWarningsRefreshPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.warningsTravelWarningsRefreshPostRaw(initOverrides);
        return await response.value();
    }

}
