/* tslint:disable */
/* eslint-disable */
/**
 * travel-warnings-service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UserTripDto,
} from '../models/index';
import {
    UserTripDtoFromJSON,
    UserTripDtoToJSON,
} from '../models/index';

export interface WarningsTripsPostRequest {
    userTripDto: Omit<UserTripDto, 'id'>;
}

export interface WarningsTripsTripIdDeleteRequest {
    tripId: number;
}

export interface WarningsTripsTripIdGetRequest {
    tripId: number;
}

export interface WarningsTripsTripIdNotificationsPatchRequest {
    tripId: number;
    enabled?: boolean;
}

export interface WarningsTripsTripIdPutRequest {
    tripId: number;
    userTripDto: Omit<UserTripDto, 'id'>;
}

export interface WarningsTripsUserEmailGetRequest {
    email: string;
}

export interface WarningsTripsUserEmailWarningsGetRequest {
    email: string;
}

/**
 * 
 */
export class UserTripsApi extends runtime.BaseAPI {

    /**
     * Creates a new trip for receiving travel warnings. If active warnings exist for the destination, an immediate notification is sent.
     * Create a new trip
     */
    async warningsTripsPostRaw(requestParameters: WarningsTripsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['userTripDto'] == null) {
            throw new runtime.RequiredError(
                'userTripDto',
                'Required parameter "userTripDto" was null or undefined when calling warningsTripsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/warnings/trips`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserTripDtoToJSON(requestParameters['userTripDto']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Creates a new trip for receiving travel warnings. If active warnings exist for the destination, an immediate notification is sent.
     * Create a new trip
     */
    async warningsTripsPost(requestParameters: WarningsTripsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.warningsTripsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a trip and stops alerts for it
     * Delete a trip
     */
    async warningsTripsTripIdDeleteRaw(requestParameters: WarningsTripsTripIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['tripId'] == null) {
            throw new runtime.RequiredError(
                'tripId',
                'Required parameter "tripId" was null or undefined when calling warningsTripsTripIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/warnings/trips/{tripId}`;
        urlPath = urlPath.replace(`{${"tripId"}}`, encodeURIComponent(String(requestParameters['tripId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Deletes a trip and stops alerts for it
     * Delete a trip
     */
    async warningsTripsTripIdDelete(requestParameters: WarningsTripsTripIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.warningsTripsTripIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a specific trip by its ID
     * Get trip by ID
     */
    async warningsTripsTripIdGetRaw(requestParameters: WarningsTripsTripIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['tripId'] == null) {
            throw new runtime.RequiredError(
                'tripId',
                'Required parameter "tripId" was null or undefined when calling warningsTripsTripIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/warnings/trips/{tripId}`;
        urlPath = urlPath.replace(`{${"tripId"}}`, encodeURIComponent(String(requestParameters['tripId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Returns a specific trip by its ID
     * Get trip by ID
     */
    async warningsTripsTripIdGet(requestParameters: WarningsTripsTripIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.warningsTripsTripIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Enable or disable notifications for a trip
     * Toggle notifications
     */
    async warningsTripsTripIdNotificationsPatchRaw(requestParameters: WarningsTripsTripIdNotificationsPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['tripId'] == null) {
            throw new runtime.RequiredError(
                'tripId',
                'Required parameter "tripId" was null or undefined when calling warningsTripsTripIdNotificationsPatch().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['enabled'] != null) {
            queryParameters['enabled'] = requestParameters['enabled'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/warnings/trips/{tripId}/notifications`;
        urlPath = urlPath.replace(`{${"tripId"}}`, encodeURIComponent(String(requestParameters['tripId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Enable or disable notifications for a trip
     * Toggle notifications
     */
    async warningsTripsTripIdNotificationsPatch(requestParameters: WarningsTripsTripIdNotificationsPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.warningsTripsTripIdNotificationsPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates an existing trip
     * Update a trip
     */
    async warningsTripsTripIdPutRaw(requestParameters: WarningsTripsTripIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['tripId'] == null) {
            throw new runtime.RequiredError(
                'tripId',
                'Required parameter "tripId" was null or undefined when calling warningsTripsTripIdPut().'
            );
        }

        if (requestParameters['userTripDto'] == null) {
            throw new runtime.RequiredError(
                'userTripDto',
                'Required parameter "userTripDto" was null or undefined when calling warningsTripsTripIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/warnings/trips/{tripId}`;
        urlPath = urlPath.replace(`{${"tripId"}}`, encodeURIComponent(String(requestParameters['tripId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UserTripDtoToJSON(requestParameters['userTripDto']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Updates an existing trip
     * Update a trip
     */
    async warningsTripsTripIdPut(requestParameters: WarningsTripsTripIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.warningsTripsTripIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all trips associated with a user email
     * Get all trips for a user
     */
    async warningsTripsUserEmailGetRaw(requestParameters: WarningsTripsUserEmailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling warningsTripsUserEmailGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/warnings/trips/user/{email}`;
        urlPath = urlPath.replace(`{${"email"}}`, encodeURIComponent(String(requestParameters['email'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Returns all trips associated with a user email
     * Get all trips for a user
     */
    async warningsTripsUserEmailGet(requestParameters: WarningsTripsUserEmailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.warningsTripsUserEmailGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all active warnings that affect the user\'s trips
     * Get warnings for user\'s trips
     */
    async warningsTripsUserEmailWarningsGetRaw(requestParameters: WarningsTripsUserEmailWarningsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling warningsTripsUserEmailWarningsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/warnings/trips/user/{email}/warnings`;
        urlPath = urlPath.replace(`{${"email"}}`, encodeURIComponent(String(requestParameters['email'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Returns all active warnings that affect the user\'s trips
     * Get warnings for user\'s trips
     */
    async warningsTripsUserEmailWarningsGet(requestParameters: WarningsTripsUserEmailWarningsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.warningsTripsUserEmailWarningsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
