/* tslint:disable */
/* eslint-disable */
/**
 * Travel App API
 * API for managing travel itineraries, locations, and social interactions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthenticatedUser,
} from '../models/index';
import {
    AuthenticatedUserFromJSON,
    AuthenticatedUserToJSON,
} from '../models/index';

/**
 * 
 */
export class AuthenticationApi extends runtime.BaseAPI {

    /**
     * Public endpoint to check if authentication system is working. Does not require authentication.
     * Health check endpoint
     */
    async authHealthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/health`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Public endpoint to check if authentication system is working. Does not require authentication.
     * Health check endpoint
     */
    async authHealthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authHealthGetRaw(initOverrides);
    }

    /**
     * Returns the authenticated user\'s information from the Identity Platform token. Requires valid Identity Platform ID token in Authorization header.
     * Get current user information
     */
    async authMeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthenticatedUser>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthenticatedUserFromJSON(jsonValue));
    }

    /**
     * Returns the authenticated user\'s information from the Identity Platform token. Requires valid Identity Platform ID token in Authorization header.
     * Get current user information
     */
    async authMeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthenticatedUser> {
        const response = await this.authMeGetRaw(initOverrides);
        return await response.value();
    }

}
