/* tslint:disable */
/* eslint-disable */
/**
 * Travel App API
 * API for managing travel itineraries, locations, and social interactions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LikeDto,
  LikeResponseDto,
  MessageResponseDto1,
} from '../models/index';
import {
    LikeDtoFromJSON,
    LikeDtoToJSON,
    LikeResponseDtoFromJSON,
    LikeResponseDtoToJSON,
    MessageResponseDto1FromJSON,
    MessageResponseDto1ToJSON,
} from '../models/index';

export interface LikeItineraryItineraryIdDeleteRequest {
    itineraryId: number;
}

export interface LikeItineraryItineraryIdGetRequest {
    itineraryId: number;
}

export interface LikeItineraryItineraryIdPostRequest {
    itineraryId: number;
}

/**
 * 
 */
export class LikeManagementApi extends runtime.BaseAPI {

    /**
     * Removes a like from an itinerary. Requires authentication.
     * Remove like from itinerary
     */
    async likeItineraryItineraryIdDeleteRaw(requestParameters: LikeItineraryItineraryIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageResponseDto1>> {
        if (requestParameters['itineraryId'] == null) {
            throw new runtime.RequiredError(
                'itineraryId',
                'Required parameter "itineraryId" was null or undefined when calling likeItineraryItineraryIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/like/itinerary/{itineraryId}`;
        urlPath = urlPath.replace(`{${"itineraryId"}}`, encodeURIComponent(String(requestParameters['itineraryId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageResponseDto1FromJSON(jsonValue));
    }

    /**
     * Removes a like from an itinerary. Requires authentication.
     * Remove like from itinerary
     */
    async likeItineraryItineraryIdDelete(requestParameters: LikeItineraryItineraryIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageResponseDto1> {
        const response = await this.likeItineraryItineraryIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves the number of likes for a specific itinerary. Requires authentication.
     * Get like count for itinerary
     */
    async likeItineraryItineraryIdGetRaw(requestParameters: LikeItineraryItineraryIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LikeResponseDto>> {
        if (requestParameters['itineraryId'] == null) {
            throw new runtime.RequiredError(
                'itineraryId',
                'Required parameter "itineraryId" was null or undefined when calling likeItineraryItineraryIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/like/itinerary/{itineraryId}`;
        urlPath = urlPath.replace(`{${"itineraryId"}}`, encodeURIComponent(String(requestParameters['itineraryId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LikeResponseDtoFromJSON(jsonValue));
    }

    /**
     * Retrieves the number of likes for a specific itinerary. Requires authentication.
     * Get like count for itinerary
     */
    async likeItineraryItineraryIdGet(requestParameters: LikeItineraryItineraryIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LikeResponseDto> {
        const response = await this.likeItineraryItineraryIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Adds a like to an itinerary. Requires authentication. Users can only like once per itinerary.
     * Like an itinerary
     */
    async likeItineraryItineraryIdPostRaw(requestParameters: LikeItineraryItineraryIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LikeDto>> {
        if (requestParameters['itineraryId'] == null) {
            throw new runtime.RequiredError(
                'itineraryId',
                'Required parameter "itineraryId" was null or undefined when calling likeItineraryItineraryIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/like/itinerary/{itineraryId}`;
        urlPath = urlPath.replace(`{${"itineraryId"}}`, encodeURIComponent(String(requestParameters['itineraryId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LikeDtoFromJSON(jsonValue));
    }

    /**
     * Adds a like to an itinerary. Requires authentication. Users can only like once per itinerary.
     * Like an itinerary
     */
    async likeItineraryItineraryIdPost(requestParameters: LikeItineraryItineraryIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LikeDto> {
        const response = await this.likeItineraryItineraryIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves all likes made by the authenticated user. Requires authentication.
     * Get likes by user
     */
    async likeUserGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LikeDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/like/user`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LikeDtoFromJSON));
    }

    /**
     * Retrieves all likes made by the authenticated user. Requires authentication.
     * Get likes by user
     */
    async likeUserGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LikeDto>> {
        const response = await this.likeUserGetRaw(initOverrides);
        return await response.value();
    }

}
