/* tslint:disable */
/* eslint-disable */
/**
 * weather-forecast-service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DailyForecastResponse
 */
export interface DailyForecastResponse {
    /**
     * 
     * @type {string}
     * @memberof DailyForecastResponse
     */
    date?: string;
    /**
     * 
     * @type {number}
     * @memberof DailyForecastResponse
     */
    temperatureHigh?: number;
    /**
     * 
     * @type {number}
     * @memberof DailyForecastResponse
     */
    temperatureLow?: number;
    /**
     * 
     * @type {string}
     * @memberof DailyForecastResponse
     */
    weather?: string;
    /**
     * 
     * @type {string}
     * @memberof DailyForecastResponse
     */
    weatherIcon?: string;
    /**
     * 
     * @type {number}
     * @memberof DailyForecastResponse
     */
    precipitationProbability?: number;
    /**
     * 
     * @type {number}
     * @memberof DailyForecastResponse
     */
    precipitationTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof DailyForecastResponse
     */
    windSpeed?: number;
    /**
     * 
     * @type {number}
     * @memberof DailyForecastResponse
     */
    windDirection?: number;
    /**
     * 
     * @type {number}
     * @memberof DailyForecastResponse
     */
    humidity?: number;
    /**
     * 
     * @type {number}
     * @memberof DailyForecastResponse
     */
    uvIndex?: number;
    /**
     * 
     * @type {string}
     * @memberof DailyForecastResponse
     */
    summary?: string;
}

/**
 * Check if a given object implements the DailyForecastResponse interface.
 */
export function instanceOfDailyForecastResponse(value: object): value is DailyForecastResponse {
    return true;
}

export function DailyForecastResponseFromJSON(json: any): DailyForecastResponse {
    return DailyForecastResponseFromJSONTyped(json, false);
}

export function DailyForecastResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DailyForecastResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : json['date'],
        'temperatureHigh': json['temperatureHigh'] == null ? undefined : json['temperatureHigh'],
        'temperatureLow': json['temperatureLow'] == null ? undefined : json['temperatureLow'],
        'weather': json['weather'] == null ? undefined : json['weather'],
        'weatherIcon': json['weatherIcon'] == null ? undefined : json['weatherIcon'],
        'precipitationProbability': json['precipitationProbability'] == null ? undefined : json['precipitationProbability'],
        'precipitationTotal': json['precipitationTotal'] == null ? undefined : json['precipitationTotal'],
        'windSpeed': json['windSpeed'] == null ? undefined : json['windSpeed'],
        'windDirection': json['windDirection'] == null ? undefined : json['windDirection'],
        'humidity': json['humidity'] == null ? undefined : json['humidity'],
        'uvIndex': json['uvIndex'] == null ? undefined : json['uvIndex'],
        'summary': json['summary'] == null ? undefined : json['summary'],
    };
}

export function DailyForecastResponseToJSON(json: any): DailyForecastResponse {
    return DailyForecastResponseToJSONTyped(json, false);
}

export function DailyForecastResponseToJSONTyped(value?: DailyForecastResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'temperatureHigh': value['temperatureHigh'],
        'temperatureLow': value['temperatureLow'],
        'weather': value['weather'],
        'weatherIcon': value['weatherIcon'],
        'precipitationProbability': value['precipitationProbability'],
        'precipitationTotal': value['precipitationTotal'],
        'windSpeed': value['windSpeed'],
        'windDirection': value['windDirection'],
        'humidity': value['humidity'],
        'uvIndex': value['uvIndex'],
        'summary': value['summary'],
    };
}

