/* tslint:disable */
/* eslint-disable */
/**
 * weather-forecast-service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HourlyForecastResponse
 */
export interface HourlyForecastResponse {
    /**
     * 
     * @type {string}
     * @memberof HourlyForecastResponse
     */
    date?: string;
    /**
     * 
     * @type {number}
     * @memberof HourlyForecastResponse
     */
    temperature?: number;
    /**
     * 
     * @type {string}
     * @memberof HourlyForecastResponse
     */
    weather?: string;
    /**
     * 
     * @type {string}
     * @memberof HourlyForecastResponse
     */
    weatherIcon?: string;
    /**
     * 
     * @type {number}
     * @memberof HourlyForecastResponse
     */
    precipitationTotal?: number;
    /**
     * 
     * @type {string}
     * @memberof HourlyForecastResponse
     */
    precipitationType?: string;
    /**
     * 
     * @type {number}
     * @memberof HourlyForecastResponse
     */
    windSpeed?: number;
    /**
     * 
     * @type {number}
     * @memberof HourlyForecastResponse
     */
    windDirection?: number;
    /**
     * 
     * @type {number}
     * @memberof HourlyForecastResponse
     */
    cloudCover?: number;
    /**
     * 
     * @type {string}
     * @memberof HourlyForecastResponse
     */
    summary?: string;
}

/**
 * Check if a given object implements the HourlyForecastResponse interface.
 */
export function instanceOfHourlyForecastResponse(value: object): value is HourlyForecastResponse {
    return true;
}

export function HourlyForecastResponseFromJSON(json: any): HourlyForecastResponse {
    return HourlyForecastResponseFromJSONTyped(json, false);
}

export function HourlyForecastResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HourlyForecastResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : json['date'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'weather': json['weather'] == null ? undefined : json['weather'],
        'weatherIcon': json['weatherIcon'] == null ? undefined : json['weatherIcon'],
        'precipitationTotal': json['precipitationTotal'] == null ? undefined : json['precipitationTotal'],
        'precipitationType': json['precipitationType'] == null ? undefined : json['precipitationType'],
        'windSpeed': json['windSpeed'] == null ? undefined : json['windSpeed'],
        'windDirection': json['windDirection'] == null ? undefined : json['windDirection'],
        'cloudCover': json['cloudCover'] == null ? undefined : json['cloudCover'],
        'summary': json['summary'] == null ? undefined : json['summary'],
    };
}

export function HourlyForecastResponseToJSON(json: any): HourlyForecastResponse {
    return HourlyForecastResponseToJSONTyped(json, false);
}

export function HourlyForecastResponseToJSONTyped(value?: HourlyForecastResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'temperature': value['temperature'],
        'weather': value['weather'],
        'weatherIcon': value['weatherIcon'],
        'precipitationTotal': value['precipitationTotal'],
        'precipitationType': value['precipitationType'],
        'windSpeed': value['windSpeed'],
        'windDirection': value['windDirection'],
        'cloudCover': value['cloudCover'],
        'summary': value['summary'],
    };
}

