/* tslint:disable */
/* eslint-disable */
/**
 * weather-forecast-service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DailyForecastResponse } from './DailyForecastResponse';
import {
    DailyForecastResponseFromJSON,
    DailyForecastResponseFromJSONTyped,
    DailyForecastResponseToJSON,
    DailyForecastResponseToJSONTyped,
} from './DailyForecastResponse';
import type { HourlyForecastResponse } from './HourlyForecastResponse';
import {
    HourlyForecastResponseFromJSON,
    HourlyForecastResponseFromJSONTyped,
    HourlyForecastResponseToJSON,
    HourlyForecastResponseToJSONTyped,
} from './HourlyForecastResponse';

/**
 * 
 * @export
 * @interface WeatherForecastResponse
 */
export interface WeatherForecastResponse {
    /**
     * 
     * @type {number}
     * @memberof WeatherForecastResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WeatherForecastResponse
     */
    location?: string;
    /**
     * 
     * @type {number}
     * @memberof WeatherForecastResponse
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof WeatherForecastResponse
     */
    longitude?: number;
    /**
     * 
     * @type {string}
     * @memberof WeatherForecastResponse
     */
    timezone?: string;
    /**
     * 
     * @type {Date}
     * @memberof WeatherForecastResponse
     */
    lastUpdated?: Date;
    /**
     * 
     * @type {Array<DailyForecastResponse>}
     * @memberof WeatherForecastResponse
     */
    dailyForecasts?: Array<DailyForecastResponse>;
    /**
     * 
     * @type {Array<HourlyForecastResponse>}
     * @memberof WeatherForecastResponse
     */
    hourlyForecasts?: Array<HourlyForecastResponse>;
}

/**
 * Check if a given object implements the WeatherForecastResponse interface.
 */
export function instanceOfWeatherForecastResponse(value: object): value is WeatherForecastResponse {
    return true;
}

export function WeatherForecastResponseFromJSON(json: any): WeatherForecastResponse {
    return WeatherForecastResponseFromJSONTyped(json, false);
}

export function WeatherForecastResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeatherForecastResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'location': json['location'] == null ? undefined : json['location'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'lastUpdated': json['lastUpdated'] == null ? undefined : (new Date(json['lastUpdated'])),
        'dailyForecasts': json['dailyForecasts'] == null ? undefined : ((json['dailyForecasts'] as Array<any>).map(DailyForecastResponseFromJSON)),
        'hourlyForecasts': json['hourlyForecasts'] == null ? undefined : ((json['hourlyForecasts'] as Array<any>).map(HourlyForecastResponseFromJSON)),
    };
}

export function WeatherForecastResponseToJSON(json: any): WeatherForecastResponse {
    return WeatherForecastResponseToJSONTyped(json, false);
}

export function WeatherForecastResponseToJSONTyped(value?: WeatherForecastResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'location': value['location'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'timezone': value['timezone'],
        'lastUpdated': value['lastUpdated'] == null ? undefined : ((value['lastUpdated']).toISOString()),
        'dailyForecasts': value['dailyForecasts'] == null ? undefined : ((value['dailyForecasts'] as Array<any>).map(DailyForecastResponseToJSON)),
        'hourlyForecasts': value['hourlyForecasts'] == null ? undefined : ((value['hourlyForecasts'] as Array<any>).map(HourlyForecastResponseToJSON)),
    };
}

