/* tslint:disable */
/* eslint-disable */
/**
 * Travel App API
 * API for managing travel itineraries, locations, and social interactions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticatedUser
 */
export interface AuthenticatedUser {
    /**
     * 
     * @type {string}
     * @memberof AuthenticatedUser
     */
    uid?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticatedUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticatedUser
     */
    name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticatedUser
     */
    emailVerified?: boolean;
}

/**
 * Check if a given object implements the AuthenticatedUser interface.
 */
export function instanceOfAuthenticatedUser(value: object): value is AuthenticatedUser {
    return true;
}

export function AuthenticatedUserFromJSON(json: any): AuthenticatedUser {
    return AuthenticatedUserFromJSONTyped(json, false);
}

export function AuthenticatedUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticatedUser {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'emailVerified': json['emailVerified'] == null ? undefined : json['emailVerified'],
    };
}

export function AuthenticatedUserToJSON(json: any): AuthenticatedUser {
    return AuthenticatedUserToJSONTyped(json, false);
}

export function AuthenticatedUserToJSONTyped(value?: AuthenticatedUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
        'email': value['email'],
        'name': value['name'],
        'emailVerified': value['emailVerified'],
    };
}

