/* tslint:disable */
/* eslint-disable */
/**
 * Travel App API
 * API for managing travel itineraries, locations, and social interactions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageUrlsDto
 */
export interface ImageUrlsDto {
    /**
     * List of image URLs (filenames) to add to the location
     * @type {Array<string>}
     * @memberof ImageUrlsDto
     */
    imageUrls: Array<string>;
}

/**
 * Check if a given object implements the ImageUrlsDto interface.
 */
export function instanceOfImageUrlsDto(value: object): value is ImageUrlsDto {
    if (!('imageUrls' in value) || value['imageUrls'] === undefined) return false;
    return true;
}

export function ImageUrlsDtoFromJSON(json: any): ImageUrlsDto {
    return ImageUrlsDtoFromJSONTyped(json, false);
}

export function ImageUrlsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageUrlsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'imageUrls': json['imageUrls'],
    };
}

export function ImageUrlsDtoToJSON(json: any): ImageUrlsDto {
    return ImageUrlsDtoToJSONTyped(json, false);
}

export function ImageUrlsDtoToJSONTyped(value?: ImageUrlsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'imageUrls': value['imageUrls'],
    };
}

