/* tslint:disable */
/* eslint-disable */
/**
 * Travel App API
 * API for managing travel itineraries, locations, and social interactions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItinerarySearchDto
 */
export interface ItinerarySearchDto {
    /**
     * 
     * @type {string}
     * @memberof ItinerarySearchDto
     */
    userName?: string;
    /**
     * 
     * @type {string}
     * @memberof ItinerarySearchDto
     */
    userEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof ItinerarySearchDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ItinerarySearchDto
     */
    destination?: string;
    /**
     * 
     * @type {string}
     * @memberof ItinerarySearchDto
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof ItinerarySearchDto
     */
    startDateFrom?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ItinerarySearchDto
     */
    startDateTo?: Date;
}

/**
 * Check if a given object implements the ItinerarySearchDto interface.
 */
export function instanceOfItinerarySearchDto(value: object): value is ItinerarySearchDto {
    return true;
}

export function ItinerarySearchDtoFromJSON(json: any): ItinerarySearchDto {
    return ItinerarySearchDtoFromJSONTyped(json, false);
}

export function ItinerarySearchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItinerarySearchDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userName': json['userName'] == null ? undefined : json['userName'],
        'userEmail': json['userEmail'] == null ? undefined : json['userEmail'],
        'title': json['title'] == null ? undefined : json['title'],
        'destination': json['destination'] == null ? undefined : json['destination'],
        'description': json['description'] == null ? undefined : json['description'],
        'startDateFrom': json['startDateFrom'] == null ? undefined : (new Date(json['startDateFrom'])),
        'startDateTo': json['startDateTo'] == null ? undefined : (new Date(json['startDateTo'])),
    };
}

export function ItinerarySearchDtoToJSON(json: any): ItinerarySearchDto {
    return ItinerarySearchDtoToJSONTyped(json, false);
}

export function ItinerarySearchDtoToJSONTyped(value?: ItinerarySearchDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userName': value['userName'],
        'userEmail': value['userEmail'],
        'title': value['title'],
        'destination': value['destination'],
        'description': value['description'],
        'startDateFrom': value['startDateFrom'] == null ? undefined : ((value['startDateFrom']).toISOString().substring(0,10)),
        'startDateTo': value['startDateTo'] == null ? undefined : ((value['startDateTo']).toISOString().substring(0,10)),
    };
}

