/* tslint:disable */
/* eslint-disable */
/**
 * Travel App API
 * API for managing travel itineraries, locations, and social interactions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItineraryDto
 */
export interface ItineraryDto {
    /**
     * 
     * @type {number}
     * @memberof ItineraryDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ItineraryDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ItineraryDto
     */
    destination?: string;
    /**
     * 
     * @type {Date}
     * @memberof ItineraryDto
     */
    startDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ItineraryDto
     */
    shortDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof ItineraryDto
     */
    detailedDescription?: string;
}

/**
 * Check if a given object implements the ItineraryDto interface.
 */
export function instanceOfItineraryDto(value: object): value is ItineraryDto {
    return true;
}

export function ItineraryDtoFromJSON(json: any): ItineraryDto {
    return ItineraryDtoFromJSONTyped(json, false);
}

export function ItineraryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItineraryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'destination': json['destination'] == null ? undefined : json['destination'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'shortDescription': json['shortDescription'] == null ? undefined : json['shortDescription'],
        'detailedDescription': json['detailedDescription'] == null ? undefined : json['detailedDescription'],
    };
}

export function ItineraryDtoToJSON(json: any): ItineraryDto {
    return ItineraryDtoToJSONTyped(json, false);
}

export function ItineraryDtoToJSONTyped(value?: ItineraryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'destination': value['destination'],
        'startDate': value['startDate'] == null ? undefined : ((value['startDate']).toISOString().substring(0,10)),
        'shortDescription': value['shortDescription'],
        'detailedDescription': value['detailedDescription'],
    };
}

