/* tslint:disable */
/* eslint-disable */
/**
 * Travel App API
 * API for managing travel itineraries, locations, and social interactions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransportDto } from './TransportDto';
import {
    TransportDtoFromJSON,
    TransportDtoFromJSONTyped,
    TransportDtoToJSON,
    TransportDtoToJSONTyped,
} from './TransportDto';
import type { AccommodationDto } from './AccommodationDto';
import {
    AccommodationDtoFromJSON,
    AccommodationDtoFromJSONTyped,
    AccommodationDtoToJSON,
    AccommodationDtoToJSONTyped,
} from './AccommodationDto';

/**
 * 
 * @export
 * @interface LocationDto
 */
export interface LocationDto {
    /**
     * 
     * @type {number}
     * @memberof LocationDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof LocationDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof LocationDto
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof LocationDto
     */
    fromDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof LocationDto
     */
    toDate?: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof LocationDto
     */
    imageUrls?: Array<string>;
    /**
     * 
     * @type {TransportDto}
     * @memberof LocationDto
     */
    transportDto?: TransportDto;
    /**
     * 
     * @type {AccommodationDto}
     * @memberof LocationDto
     */
    accommodationDto?: AccommodationDto;
}

/**
 * Check if a given object implements the LocationDto interface.
 */
export function instanceOfLocationDto(value: object): value is LocationDto {
    return true;
}

export function LocationDtoFromJSON(json: any): LocationDto {
    return LocationDtoFromJSONTyped(json, false);
}

export function LocationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'fromDate': json['fromDate'] == null ? undefined : (new Date(json['fromDate'])),
        'toDate': json['toDate'] == null ? undefined : (new Date(json['toDate'])),
        'imageUrls': json['imageUrls'] == null ? undefined : json['imageUrls'],
        'transportDto': json['transportDto'] == null ? undefined : TransportDtoFromJSON(json['transportDto']),
        'accommodationDto': json['accommodationDto'] == null ? undefined : AccommodationDtoFromJSON(json['accommodationDto']),
    };
}

export function LocationDtoToJSON(json: any): LocationDto {
    return LocationDtoToJSONTyped(json, false);
}

export function LocationDtoToJSONTyped(value?: LocationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'fromDate': value['fromDate'] == null ? undefined : ((value['fromDate']).toISOString().substring(0,10)),
        'toDate': value['toDate'] == null ? undefined : ((value['toDate']).toISOString().substring(0,10)),
        'imageUrls': value['imageUrls'],
        'transportDto': TransportDtoToJSON(value['transportDto']),
        'accommodationDto': AccommodationDtoToJSON(value['accommodationDto']),
    };
}

