/* tslint:disable */
/* eslint-disable */
/**
 * Travel App API
 * API for managing travel itineraries, locations, and social interactions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response object for location image upload operations
 * @export
 * @interface LocationImageUploadResponseDto
 */
export interface LocationImageUploadResponseDto {
    /**
     * Success message
     * @type {string}
     * @memberof LocationImageUploadResponseDto
     */
    message?: string;
    /**
     * List of uploaded image URLs
     * @type {Array<string>}
     * @memberof LocationImageUploadResponseDto
     */
    imageUrls?: Array<string>;
}

/**
 * Check if a given object implements the LocationImageUploadResponseDto interface.
 */
export function instanceOfLocationImageUploadResponseDto(value: object): value is LocationImageUploadResponseDto {
    return true;
}

export function LocationImageUploadResponseDtoFromJSON(json: any): LocationImageUploadResponseDto {
    return LocationImageUploadResponseDtoFromJSONTyped(json, false);
}

export function LocationImageUploadResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationImageUploadResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'imageUrls': json['imageUrls'] == null ? undefined : json['imageUrls'],
    };
}

export function LocationImageUploadResponseDtoToJSON(json: any): LocationImageUploadResponseDto {
    return LocationImageUploadResponseDtoToJSONTyped(json, false);
}

export function LocationImageUploadResponseDtoToJSONTyped(value?: LocationImageUploadResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'imageUrls': value['imageUrls'],
    };
}

