/* tslint:disable */
/* eslint-disable */
/**
 * Travel App API
 * API for managing travel itineraries, locations, and social interactions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response object for profile image upload operations
 * @export
 * @interface ProfileImageUploadResponseDto
 */
export interface ProfileImageUploadResponseDto {
    /**
     * Success message
     * @type {string}
     * @memberof ProfileImageUploadResponseDto
     */
    message?: string;
    /**
     * URL of the uploaded image
     * @type {string}
     * @memberof ProfileImageUploadResponseDto
     */
    imageUrl?: string;
}

/**
 * Check if a given object implements the ProfileImageUploadResponseDto interface.
 */
export function instanceOfProfileImageUploadResponseDto(value: object): value is ProfileImageUploadResponseDto {
    return true;
}

export function ProfileImageUploadResponseDtoFromJSON(json: any): ProfileImageUploadResponseDto {
    return ProfileImageUploadResponseDtoFromJSONTyped(json, false);
}

export function ProfileImageUploadResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileImageUploadResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
    };
}

export function ProfileImageUploadResponseDtoToJSON(json: any): ProfileImageUploadResponseDto {
    return ProfileImageUploadResponseDtoToJSONTyped(json, false);
}

export function ProfileImageUploadResponseDtoToJSONTyped(value?: ProfileImageUploadResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'imageUrl': value['imageUrl'],
    };
}

