/* tslint:disable */
/* eslint-disable */
/**
 * Travel App API
 * API for managing travel itineraries, locations, and social interactions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransportDto
 */
export interface TransportDto {
    /**
     * 
     * @type {number}
     * @memberof TransportDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TransportDto
     */
    transportType?: string;
    /**
     * 
     * @type {number}
     * @memberof TransportDto
     */
    duration?: number;
    /**
     * 
     * @type {number}
     * @memberof TransportDto
     */
    distance?: number;
}

/**
 * Check if a given object implements the TransportDto interface.
 */
export function instanceOfTransportDto(value: object): value is TransportDto {
    return true;
}

export function TransportDtoFromJSON(json: any): TransportDto {
    return TransportDtoFromJSONTyped(json, false);
}

export function TransportDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransportDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'transportType': json['transportType'] == null ? undefined : json['transportType'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'distance': json['distance'] == null ? undefined : json['distance'],
    };
}

export function TransportDtoToJSON(json: any): TransportDto {
    return TransportDtoToJSONTyped(json, false);
}

export function TransportDtoToJSONTyped(value?: TransportDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'transportType': value['transportType'],
        'duration': value['duration'],
        'distance': value['distance'],
    };
}

