/* tslint:disable */
/* eslint-disable */
/**
 * weather-forecast-service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';


/**
 * WeatherForecastResourceApi - axios parameter creator
 * @export
 */
export const WeatherForecastResourceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get Weather Forecast By Coordinates
         * @param {number} [lat] 
         * @param {number} [lon] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWeatherForecastCoordinatesGet: async (lat?: number, lon?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/weather/forecast/coordinates`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (lat !== undefined) {
                localVarQueryParameter['lat'] = lat;
            }

            if (lon !== undefined) {
                localVarQueryParameter['lon'] = lon;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Fetch Weather Forecast By Coordinates
         * @param {number} [lat] 
         * @param {string} [location] 
         * @param {number} [lon] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWeatherForecastCoordinatesPost: async (lat?: number, location?: string, lon?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/weather/forecast/coordinates`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (lat !== undefined) {
                localVarQueryParameter['lat'] = lat;
            }

            if (location !== undefined) {
                localVarQueryParameter['location'] = location;
            }

            if (lon !== undefined) {
                localVarQueryParameter['lon'] = lon;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Weather Forecast By Location
         * @param {string} [location] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWeatherForecastLocationDelete: async (location?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/weather/forecast/location`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (location !== undefined) {
                localVarQueryParameter['location'] = location;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Weather Forecast By Location
         * @param {string} [location] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWeatherForecastLocationGet: async (location?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/weather/forecast/location`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (location !== undefined) {
                localVarQueryParameter['location'] = location;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get All Weather Forecasts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWeatherForecastsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/weather/forecasts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WeatherForecastResourceApi - functional programming interface
 * @export
 */
export const WeatherForecastResourceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WeatherForecastResourceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get Weather Forecast By Coordinates
         * @param {number} [lat] 
         * @param {number} [lon] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWeatherForecastCoordinatesGet(lat?: number, lon?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiWeatherForecastCoordinatesGet(lat, lon, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WeatherForecastResourceApi.apiWeatherForecastCoordinatesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Fetch Weather Forecast By Coordinates
         * @param {number} [lat] 
         * @param {string} [location] 
         * @param {number} [lon] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWeatherForecastCoordinatesPost(lat?: number, location?: string, lon?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiWeatherForecastCoordinatesPost(lat, location, lon, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WeatherForecastResourceApi.apiWeatherForecastCoordinatesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete Weather Forecast By Location
         * @param {string} [location] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWeatherForecastLocationDelete(location?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiWeatherForecastLocationDelete(location, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WeatherForecastResourceApi.apiWeatherForecastLocationDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Weather Forecast By Location
         * @param {string} [location] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWeatherForecastLocationGet(location?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiWeatherForecastLocationGet(location, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WeatherForecastResourceApi.apiWeatherForecastLocationGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get All Weather Forecasts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWeatherForecastsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiWeatherForecastsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WeatherForecastResourceApi.apiWeatherForecastsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WeatherForecastResourceApi - factory interface
 * @export
 */
export const WeatherForecastResourceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WeatherForecastResourceApiFp(configuration)
    return {
        /**
         * 
         * @summary Get Weather Forecast By Coordinates
         * @param {number} [lat] 
         * @param {number} [lon] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWeatherForecastCoordinatesGet(lat?: number, lon?: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiWeatherForecastCoordinatesGet(lat, lon, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Fetch Weather Forecast By Coordinates
         * @param {number} [lat] 
         * @param {string} [location] 
         * @param {number} [lon] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWeatherForecastCoordinatesPost(lat?: number, location?: string, lon?: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiWeatherForecastCoordinatesPost(lat, location, lon, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete Weather Forecast By Location
         * @param {string} [location] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWeatherForecastLocationDelete(location?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiWeatherForecastLocationDelete(location, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Weather Forecast By Location
         * @param {string} [location] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWeatherForecastLocationGet(location?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiWeatherForecastLocationGet(location, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get All Weather Forecasts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWeatherForecastsGet(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiWeatherForecastsGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WeatherForecastResourceApi - object-oriented interface
 * @export
 * @class WeatherForecastResourceApi
 * @extends {BaseAPI}
 */
export class WeatherForecastResourceApi extends BaseAPI {
    /**
     * 
     * @summary Get Weather Forecast By Coordinates
     * @param {number} [lat] 
     * @param {number} [lon] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherForecastResourceApi
     */
    public apiWeatherForecastCoordinatesGet(lat?: number, lon?: number, options?: RawAxiosRequestConfig) {
        return WeatherForecastResourceApiFp(this.configuration).apiWeatherForecastCoordinatesGet(lat, lon, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Fetch Weather Forecast By Coordinates
     * @param {number} [lat] 
     * @param {string} [location] 
     * @param {number} [lon] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherForecastResourceApi
     */
    public apiWeatherForecastCoordinatesPost(lat?: number, location?: string, lon?: number, options?: RawAxiosRequestConfig) {
        return WeatherForecastResourceApiFp(this.configuration).apiWeatherForecastCoordinatesPost(lat, location, lon, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete Weather Forecast By Location
     * @param {string} [location] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherForecastResourceApi
     */
    public apiWeatherForecastLocationDelete(location?: string, options?: RawAxiosRequestConfig) {
        return WeatherForecastResourceApiFp(this.configuration).apiWeatherForecastLocationDelete(location, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Weather Forecast By Location
     * @param {string} [location] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherForecastResourceApi
     */
    public apiWeatherForecastLocationGet(location?: string, options?: RawAxiosRequestConfig) {
        return WeatherForecastResourceApiFp(this.configuration).apiWeatherForecastLocationGet(location, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get All Weather Forecasts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherForecastResourceApi
     */
    public apiWeatherForecastsGet(options?: RawAxiosRequestConfig) {
        return WeatherForecastResourceApiFp(this.configuration).apiWeatherForecastsGet(options).then((request) => request(this.axios, this.basePath));
    }
}



