/* tslint:disable */
/* eslint-disable */
/**
 * Recommendation Service API
 * API for personalized travel itinerary recommendations and social graph management.  ## Authentication  All endpoints require authentication using Google Cloud Identity Platform (Firebase Authentication). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ItineraryEventDTO,
} from '../models/index';
import {
    ItineraryEventDTOFromJSON,
    ItineraryEventDTOToJSON,
} from '../models/index';

/**
 * 
 */
export class FeedApi extends runtime.BaseAPI {

    /**
     * Returns a personalized feed of itinerary recommendations based on the authenticated traveller\'s visited/planned destinations and social signals (likes). Falls back to basic feed for new users.
     * Get personalized feed
     */
    async feedGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ItineraryEventDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/feed`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ItineraryEventDTOFromJSON));
    }

    /**
     * Returns a personalized feed of itinerary recommendations based on the authenticated traveller\'s visited/planned destinations and social signals (likes). Falls back to basic feed for new users.
     * Get personalized feed
     */
    async feedGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ItineraryEventDTO>> {
        const response = await this.feedGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns a feed of the most popular itineraries based on likes
     * Get popular feed
     */
    async feedPopularGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ItineraryEventDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/feed/popular`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ItineraryEventDTOFromJSON));
    }

    /**
     * Returns a feed of the most popular itineraries based on likes
     * Get popular feed
     */
    async feedPopularGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ItineraryEventDTO>> {
        const response = await this.feedPopularGetRaw(initOverrides);
        return await response.value();
    }

}
