/* tslint:disable */
/* eslint-disable */
/**
 * Recommendation Service API
 * API for personalized travel itinerary recommendations and social graph management.  ## Authentication  All endpoints require authentication using Google Cloud Identity Platform (Firebase Authentication). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ItineraryEventDTO,
  LikeActionDTO,
  LocationVisitDTO,
} from '../models/index';
import {
    ItineraryEventDTOFromJSON,
    ItineraryEventDTOToJSON,
    LikeActionDTOFromJSON,
    LikeActionDTOToJSON,
    LocationVisitDTOFromJSON,
    LocationVisitDTOToJSON,
} from '../models/index';

export interface GraphItinerariesPostRequest {
    itineraryEventDTO: ItineraryEventDTO;
}

export interface GraphLikesDeleteRequest {
    likeActionDTO: LikeActionDTO;
}

export interface GraphLikesPostRequest {
    likeActionDTO: LikeActionDTO;
}

export interface GraphLocationsVisitsPostRequest {
    locationVisitDTO: LocationVisitDTO;
}

/**
 * 
 */
export class GraphApi extends runtime.BaseAPI {

    /**
     * Creates or updates an itinerary node and its relationships in the graph database for the authenticated user
     * Record an itinerary event
     */
    async graphItinerariesPostRaw(requestParameters: GraphItinerariesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['itineraryEventDTO'] == null) {
            throw new runtime.RequiredError(
                'itineraryEventDTO',
                'Required parameter "itineraryEventDTO" was null or undefined when calling graphItinerariesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/graph/itineraries`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ItineraryEventDTOToJSON(requestParameters['itineraryEventDTO']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Creates or updates an itinerary node and its relationships in the graph database for the authenticated user
     * Record an itinerary event
     */
    async graphItinerariesPost(requestParameters: GraphItinerariesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.graphItinerariesPostRaw(requestParameters, initOverrides);
    }

    /**
     * Removes a LIKES relationship between the authenticated user and an itinerary from the graph database
     * Remove a like action
     */
    async graphLikesDeleteRaw(requestParameters: GraphLikesDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['likeActionDTO'] == null) {
            throw new runtime.RequiredError(
                'likeActionDTO',
                'Required parameter "likeActionDTO" was null or undefined when calling graphLikesDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/graph/likes`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: LikeActionDTOToJSON(requestParameters['likeActionDTO']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes a LIKES relationship between the authenticated user and an itinerary from the graph database
     * Remove a like action
     */
    async graphLikesDelete(requestParameters: GraphLikesDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.graphLikesDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates a LIKES relationship between the authenticated user and an itinerary in the graph database
     * Record a like action
     */
    async graphLikesPostRaw(requestParameters: GraphLikesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['likeActionDTO'] == null) {
            throw new runtime.RequiredError(
                'likeActionDTO',
                'Required parameter "likeActionDTO" was null or undefined when calling graphLikesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/graph/likes`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LikeActionDTOToJSON(requestParameters['likeActionDTO']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Creates a LIKES relationship between the authenticated user and an itinerary in the graph database
     * Record a like action
     */
    async graphLikesPost(requestParameters: GraphLikesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.graphLikesPostRaw(requestParameters, initOverrides);
    }

    /**
     * Creates VISITED relationships between the authenticated user and locations in the graph database
     * Record location visits
     */
    async graphLocationsVisitsPostRaw(requestParameters: GraphLocationsVisitsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['locationVisitDTO'] == null) {
            throw new runtime.RequiredError(
                'locationVisitDTO',
                'Required parameter "locationVisitDTO" was null or undefined when calling graphLocationsVisitsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/graph/locations/visits`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LocationVisitDTOToJSON(requestParameters['locationVisitDTO']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Creates VISITED relationships between the authenticated user and locations in the graph database
     * Record location visits
     */
    async graphLocationsVisitsPost(requestParameters: GraphLocationsVisitsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.graphLocationsVisitsPostRaw(requestParameters, initOverrides);
    }

}
