/* tslint:disable */
/* eslint-disable */
/**
 * Travel App API
 * API for managing travel itineraries, locations, and social interactions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccommodationDto
 */
export interface AccommodationDto {
    /**
     * 
     * @type {number}
     * @memberof AccommodationDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AccommodationDto
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof AccommodationDto
     */
    pricePerNight?: number;
    /**
     * 
     * @type {number}
     * @memberof AccommodationDto
     */
    rating?: number;
    /**
     * 
     * @type {string}
     * @memberof AccommodationDto
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof AccommodationDto
     */
    accommodationImageUrl?: string;
}

/**
 * Check if a given object implements the AccommodationDto interface.
 */
export function instanceOfAccommodationDto(value: object): value is AccommodationDto {
    return true;
}

export function AccommodationDtoFromJSON(json: any): AccommodationDto {
    return AccommodationDtoFromJSONTyped(json, false);
}

export function AccommodationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccommodationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'pricePerNight': json['pricePerNight'] == null ? undefined : json['pricePerNight'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'accommodationImageUrl': json['accommodationImageUrl'] == null ? undefined : json['accommodationImageUrl'],
    };
}

export function AccommodationDtoToJSON(json: any): AccommodationDto {
    return AccommodationDtoToJSONTyped(json, false);
}

export function AccommodationDtoToJSONTyped(value?: AccommodationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'pricePerNight': value['pricePerNight'],
        'rating': value['rating'],
        'notes': value['notes'],
        'accommodationImageUrl': value['accommodationImageUrl'],
    };
}

