/* tslint:disable */
/* eslint-disable */
/**
 * Travel App API
 * API for managing travel itineraries, locations, and social interactions
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItinerarySearchResponseDto
 */
export interface ItinerarySearchResponseDto {
    /**
     * 
     * @type {number}
     * @memberof ItinerarySearchResponseDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ItinerarySearchResponseDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ItinerarySearchResponseDto
     */
    destination?: string;
    /**
     * 
     * @type {Date}
     * @memberof ItinerarySearchResponseDto
     */
    startDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ItinerarySearchResponseDto
     */
    shortDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof ItinerarySearchResponseDto
     */
    detailedDescription?: string;
    /**
     *
     * @type {string}
     * @memberof ItinerarySearchResponseDto
     */
    userName?: string;
    /**
     *
     * @type {string}
     * @memberof ItinerarySearchResponseDto
     */
    userEmail?: string;
}

/**
 * Check if a given object implements the ItinerarySearchResponseDto interface.
 */
export function instanceOfItinerarySearchResponseDto(value: object): value is ItinerarySearchResponseDto {
    return true;
}

export function ItinerarySearchResponseDtoFromJSON(json: any): ItinerarySearchResponseDto {
    return ItinerarySearchResponseDtoFromJSONTyped(json, false);
}

export function ItinerarySearchResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItinerarySearchResponseDto {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'destination': json['destination'] == null ? undefined : json['destination'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'shortDescription': json['shortDescription'] == null ? undefined : json['shortDescription'],
        'detailedDescription': json['detailedDescription'] == null ? undefined : json['detailedDescription'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'userEmail': json['userEmail'] == null ? undefined : json['userEmail'],
    };
}

export function ItinerarySearchResponseDtoToJSON(json: any): ItinerarySearchResponseDto {
    return ItinerarySearchResponseDtoToJSONTyped(json, false);
}

export function ItinerarySearchResponseDtoToJSONTyped(value?: ItinerarySearchResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'title': value['title'],
        'destination': value['destination'],
        'startDate': value['startDate'] == null ? undefined : ((value['startDate']).toISOString().substring(0,10)),
        'shortDescription': value['shortDescription'],
        'detailedDescription': value['detailedDescription'],
        'userName': value['userName'],
        'userEmail': value['userEmail'],
    };
}

