/* tslint:disable */
/* eslint-disable */
/**
 * weather-forecast-service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WeatherForecastResponse,
} from '../models/index';
import {
    WeatherForecastResponseFromJSON,
    WeatherForecastResponseToJSON,
} from '../models/index';

export interface ApiWeatherForecastCoordinatesGetRequest {
    lat?: number;
    lon?: number;
}

export interface ApiWeatherForecastCoordinatesPostRequest {
    lat?: number;
    location?: string;
    lon?: number;
}

export interface ApiWeatherForecastLocationDeleteRequest {
    location?: string;
}

export interface ApiWeatherForecastLocationGetRequest {
    location?: string;
}

/**
 * 
 */
export class WeatherForecastApi extends runtime.BaseAPI {

    /**
     * Retrieves stored weather forecasts for specific geographic coordinates. Returns all forecasts matching the latitude and longitude.
     * Get Weather Forecast By Coordinates
     */
    async apiWeatherForecastCoordinatesGetRaw(requestParameters: ApiWeatherForecastCoordinatesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WeatherForecastResponse>>> {
        const queryParameters: any = {};

        if (requestParameters['lat'] != null) {
            queryParameters['lat'] = requestParameters['lat'];
        }

        if (requestParameters['lon'] != null) {
            queryParameters['lon'] = requestParameters['lon'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/weather/forecast/coordinates`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WeatherForecastResponseFromJSON));
    }

    /**
     * Retrieves stored weather forecasts for specific geographic coordinates. Returns all forecasts matching the latitude and longitude.
     * Get Weather Forecast By Coordinates
     */
    async apiWeatherForecastCoordinatesGet(requestParameters: ApiWeatherForecastCoordinatesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WeatherForecastResponse>> {
        const response = await this.apiWeatherForecastCoordinatesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetches weather forecast data from external API and stores it in the database. Returns the forecast for the specified coordinates and location.
     * Fetch Weather Forecast By Coordinates
     */
    async apiWeatherForecastCoordinatesPostRaw(requestParameters: ApiWeatherForecastCoordinatesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WeatherForecastResponse>> {
        const queryParameters: any = {};

        if (requestParameters['lat'] != null) {
            queryParameters['lat'] = requestParameters['lat'];
        }

        if (requestParameters['location'] != null) {
            queryParameters['location'] = requestParameters['location'];
        }

        if (requestParameters['lon'] != null) {
            queryParameters['lon'] = requestParameters['lon'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/weather/forecast/coordinates`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WeatherForecastResponseFromJSON(jsonValue));
    }

    /**
     * Fetches weather forecast data from external API and stores it in the database. Returns the forecast for the specified coordinates and location.
     * Fetch Weather Forecast By Coordinates
     */
    async apiWeatherForecastCoordinatesPost(requestParameters: ApiWeatherForecastCoordinatesPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WeatherForecastResponse> {
        const response = await this.apiWeatherForecastCoordinatesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes all weather forecasts for a specific location. Returns the number of deleted forecasts. Case-insensitive location matching.
     * Delete Weather Forecast By Location
     */
    async apiWeatherForecastLocationDeleteRaw(requestParameters: ApiWeatherForecastLocationDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['location'] != null) {
            queryParameters['location'] = requestParameters['location'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/weather/forecast/location`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes all weather forecasts for a specific location. Returns the number of deleted forecasts. Case-insensitive location matching.
     * Delete Weather Forecast By Location
     */
    async apiWeatherForecastLocationDelete(requestParameters: ApiWeatherForecastLocationDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiWeatherForecastLocationDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieves stored weather forecasts for a specific location. Returns all forecasts matching the location name (case-insensitive).
     * Get Weather Forecast By Location
     */
    async apiWeatherForecastLocationGetRaw(requestParameters: ApiWeatherForecastLocationGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WeatherForecastResponse>>> {
        const queryParameters: any = {};

        if (requestParameters['location'] != null) {
            queryParameters['location'] = requestParameters['location'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/weather/forecast/location`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WeatherForecastResponseFromJSON));
    }

    /**
     * Retrieves stored weather forecasts for a specific location. Returns all forecasts matching the location name (case-insensitive).
     * Get Weather Forecast By Location
     */
    async apiWeatherForecastLocationGet(requestParameters: ApiWeatherForecastLocationGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WeatherForecastResponse>> {
        const response = await this.apiWeatherForecastLocationGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves all stored weather forecasts from the database. Returns a list of all available forecasts.
     * Get All Weather Forecasts
     */
    async apiWeatherForecastsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WeatherForecastResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/weather/forecasts`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WeatherForecastResponseFromJSON));
    }

    /**
     * Retrieves all stored weather forecasts from the database. Returns a list of all available forecasts.
     * Get All Weather Forecasts
     */
    async apiWeatherForecastsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WeatherForecastResponse>> {
        const response = await this.apiWeatherForecastsGetRaw(initOverrides);
        return await response.value();
    }

}
