/* tslint:disable */
/* eslint-disable */
/**
 * weather-forecast-service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface ApiWeatherForecastCoordinatesGetRequest {
    lat?: number;
    lon?: number;
}

export interface ApiWeatherForecastCoordinatesPostRequest {
    lat?: number;
    location?: string;
    lon?: number;
}

export interface ApiWeatherForecastLocationDeleteRequest {
    location?: string;
}

export interface ApiWeatherForecastLocationGetRequest {
    location?: string;
}

/**
 * 
 */
export class WeatherForecastResourceApi extends runtime.BaseAPI {

    /**
     * Get Weather Forecast By Coordinates
     */
    async apiWeatherForecastCoordinatesGetRaw(requestParameters: ApiWeatherForecastCoordinatesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['lat'] != null) {
            queryParameters['lat'] = requestParameters['lat'];
        }

        if (requestParameters['lon'] != null) {
            queryParameters['lon'] = requestParameters['lon'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/weather/forecast/coordinates`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get Weather Forecast By Coordinates
     */
    async apiWeatherForecastCoordinatesGet(requestParameters: ApiWeatherForecastCoordinatesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiWeatherForecastCoordinatesGetRaw(requestParameters, initOverrides);
    }

    /**
     * Fetch Weather Forecast By Coordinates
     */
    async apiWeatherForecastCoordinatesPostRaw(requestParameters: ApiWeatherForecastCoordinatesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['lat'] != null) {
            queryParameters['lat'] = requestParameters['lat'];
        }

        if (requestParameters['location'] != null) {
            queryParameters['location'] = requestParameters['location'];
        }

        if (requestParameters['lon'] != null) {
            queryParameters['lon'] = requestParameters['lon'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/weather/forecast/coordinates`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Fetch Weather Forecast By Coordinates
     */
    async apiWeatherForecastCoordinatesPost(requestParameters: ApiWeatherForecastCoordinatesPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiWeatherForecastCoordinatesPostRaw(requestParameters, initOverrides);
    }

    /**
     * Delete Weather Forecast By Location
     */
    async apiWeatherForecastLocationDeleteRaw(requestParameters: ApiWeatherForecastLocationDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['location'] != null) {
            queryParameters['location'] = requestParameters['location'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/weather/forecast/location`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Weather Forecast By Location
     */
    async apiWeatherForecastLocationDelete(requestParameters: ApiWeatherForecastLocationDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiWeatherForecastLocationDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get Weather Forecast By Location
     */
    async apiWeatherForecastLocationGetRaw(requestParameters: ApiWeatherForecastLocationGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['location'] != null) {
            queryParameters['location'] = requestParameters['location'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/weather/forecast/location`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get Weather Forecast By Location
     */
    async apiWeatherForecastLocationGet(requestParameters: ApiWeatherForecastLocationGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiWeatherForecastLocationGetRaw(requestParameters, initOverrides);
    }

    /**
     * Get All Weather Forecasts
     */
    async apiWeatherForecastsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/weather/forecasts`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get All Weather Forecasts
     */
    async apiWeatherForecastsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiWeatherForecastsGetRaw(initOverrides);
    }

}
